spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/process-center?characterEncoding=utf8&useSSL=true
    username: root
    password: root


  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
    show-sql: true

  activiti:
  ####校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false

server:
  port: 8081
  context-path: /activity
  session.timeout: 10
  tomcat.uri-encoding: UTF-8

mybatis:
  type-aliases-package: cn.saytime.bean


